# Specify the remote theme using the official Cayman theme repository.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Set your site’s title and a brief description.
title: "Multi-Modal Music Recommendation System"
description: "Nothing here yet."